url: "https://cbouy.github.io"
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Cédric Bouysset"
      comments: true
      permalink: "/blog/:year-:month-:day/:slug/"
  -
    scope:
      path: "assets/"
    values:
      sitemap: false
google_analytics: UA-139606105-1
title: cbouy
description: Cédric Bouysset's personnal website
author: Cédric Bouysset
logo: /assets/img/logoCB.png
social:
  name: Cédric Bouysset
  links:
    - https://www.linkedin.com/in/cedric-bouysset/
    - https://www.researchgate.net/profile/Cedric_Bouysset
    - https://github.com/cbouy
