url: "https://cbouy.github.io"
plugins:
  - jekyll-sitemap
  - jemoji
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "assets/"
    values:
      sitemap: false
tag_page_layout: tag_page
tag_page_dir: tags
ignored_tags: []
