url: "https://cbouy.github.io"
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll/tagging
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "/blog.html"
    values:
      permalink: "/blog/"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Cédric Bouysset"
      comments: true
      permalink: "/blog/:year-:month-:day/:slug"
  -
    scope:
      path: "assets/"
    values:
      sitemap: false
tag_page_layout: tag_page
tag_page_dir: tags
ignored_tags: []
