name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  github-pages:

    runs-on: ubuntu-latest

    steps:
    - name: Clone GitHub repo
      uses: actions/checkout@v4
    
    - name: Cache gems
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/vendor
        key: ${{ runner.os }}-vendor-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-vendor-

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.8

    # - name: Fetch CV
    #   run: |
    #     wget -O assets/pdf/Bouysset-CV.pdf https://github.com/cbouy/cv/raw/main/cv.pdf
    
    - name: Build "tags" pages
      run: python _scripts/tag_generator.py

    - name: Build and deploy
      uses: helaili/jekyll-action@2.2
      with:
        target_branch: 'gh-pages'
        token: ${{ secrets.GITHUB_TOKEN }}